### PR TITLE
Fix env seed deprecation warning

### PR DESCRIPTION
**Pull request by leovandriel**
OpenAI Gym shows deprecation warning:

    DeprecationWarning: WARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed)` instead.

Fix applies suggested change.

### CODE REVIEW

**Comment by koulanurag** [comment]
Thanks for bringing it to my notice.

The suggested change is not correct. 

Earlier, it was :
```
# some code
env.seed(0)
# some code
env.reset()
# some code
```
Your suggested change will lead to the following behavior
```
#some code
env.reset(seed=0)
#some code
env.reset()
# some code
```
This may not guarantee the seed assignment since we are resetting it again

Whereas as per the new API, we would want it to be :

```
# some code
# some code
env.reset(seed=seed)
# some code
```

**Comment by koulanurag** [comment]
I just ran the `main.py` using the command mentioned in `README.md` and algorithm seems to be running fine. Also, this was done in a` virtualenv` with python package versions specified in `requirements.txt`.

I would be happy to merge a single pull request for all the changes for new gym API. For this, we may need to change the following:

1. version change in requirements.txt
2. reset fn. changes as suggested in this pull-request
3. step fn. change as suggested in other pull request.
4. run over cart pole to ensure we get the same results as last time.

Thank you again!

**Comment by leovandriel** [comment]
Thanks @koulanurag, for your detailed response. From the [Gym docs](https://github.com/openai/gym/blob/master/gym/core.py#L181):

> If the environment already has a random number generator and `reset` is called with ``seed=None``, the RNG should not be reset

The way I read this is that calling reset with a `seed` argument sets the seed and calling reset without the `seed` argument do not change it. Let me know if I am not following our argument.

**Comment by leovandriel** [comment]
As for your suggestion to doing a single big PR, I can help with that. This will also affect the test runs, specifically with `Monitor`, see https://github.com/koulanurag/muzero-pytorch/pull/24. Would it make sense to include this as well?

Lastly, many packages are outdated, restricting this repo to Python 3.7. Have you considered updating all packages?

**Comment by koulanurag** [comment]
> Thanks @koulanurag, for your detailed response. From the [Gym docs](https://github.com/openai/gym/blob/master/gym/core.py#L181):
> 
> > If the environment already has a random number generator and `reset` is called with `seed=None`, the RNG should not be reset
> 
> The way I read this is that calling reset with a `seed` argument sets the seed and calling reset without the `seed` argument do not change it. Let me know if I am not following our argument.


Basically, I meant the following:
On [( line 166 in train.py)](https://github.com/koulanurag/muzero-pytorch/blob/master/core/train.py#L166), instead of passing seed, we just need to remove seed functionality  assignment of `new_game()`. And, pass the seed on [( line 168 in train.py)](https://github.com/koulanurag/muzero-pytorch/blob/master/core/train.py#L168)  in `reset() fn`. This may also require change over [here](https://github.com/koulanurag/muzero-pytorch/blob/master/config/classic_control/env_wrapper.py#L31).

**Comment by koulanurag** [comment]
> As for your suggestion to doing a single big PR, I can help with that. This will also affect the test runs, specifically with `Monitor`, see #24. Would it make sense to include this as well?
> 
> Lastly, many packages are outdated, restricting this repo to Python 3.7. Have you considered updating all packages?

Yes, I would be happy to take a single PR with changes to support the latest version of the gym and any other latest package version.

**Comment by leovandriel** [comment]
> On [( line 166 in train.py)](https://github.com/koulanurag/muzero-pytorch/blob/master/core/train.py#L166), instead of passing seed, we just need to remove seed functionality assignment of new_game(). And, pass the seed on [( line 168 in train.py)](https://github.com/koulanurag/muzero-pytorch/blob/master/core/train.py#L168) in reset() fn. This may also require change over [here](https://github.com/koulanurag/muzero-pytorch/blob/master/config/classic_control/env_wrapper.py#L31).

Thanks for clarifying. I updated the PR. Didn't see any need to make changes to `env_wrapper.py`, though open to suggestions.

**Comment by koulanurag** [comment]
Thanks for the change.

I will await all the changes for the gym's new version in this PR.

**Comment by leovandriel** [comment]
Are you okay with a `requirements.txt` that just pins the root packages? That is:

```
gym==0.25.1
numpy==1.23.1
ray==1.13.0
scipy==1.9.0
tensorboard==2.9.1
torch==1.12.1
```

**Comment by koulanurag** [comment]
> Are you okay with a `requirements.txt` that just pins the root packages? That is:
> 
> ```
> gym==0.25.1
> numpy==1.23.1
> ray==1.13.0
> scipy==1.9.0
> tensorboard==2.9.1
> torch==1.12.1
> ```

This should be fine.

**Comment by leovandriel** [comment]
Updated PR. Also added https://github.com/koulanurag/muzero-pytorch/pull/6, which is needed with updated packages

**Comment by koulanurag** [comment]
Thanks for the changes. I will do some runs before merging it.

**Pull request merged**
